spring.application.name=auth

# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# MONGODB
# ===============================
spring.mongodb.uri=mongodb://localhost:27017/auth_db

# ===============================
# JWT
# ===============================
jwt.secret=your-super-secret-key-your-super-secret-key
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000

# ===============================
# MAIL CONFIG
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your-email@gmail.com
spring.mail.password=your-app-password

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===============================
# LOGGING
# ===============================
logging.level.org.springframework.security=DEBUG