spring.application.name=auth

# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# MONGODB
# ===============================

spring.mongodb.uri=mongodb+srv://tokery_db_user:vjzPga6AZJFhvYKC@cluster0.xkgmaxe.mongodb.net/Cluster0?retryWrites=true&w=majority

# ===============================
# JWT

# ===============================
jwt.secret=dGhpcyBpcyBhIHZlcnkgbG9uZyBzZWNyZXQga2V5IGZvciBqd3Qgc2lnbmluZw==
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000

# ===============================
# MAIL CONFIG
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your-email@gmail.com
spring.mail.password=your-app-password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===============================
# LOGGING
# ===============================
logging.level.org.springframework.security=DEBUG

# ===============================
# CLOUDINARY
# ===============================
cloudinary.cloud-name=Root
cloudinary.api-key=512538536167172
cloudinary.api-secret=LyI6CWe-toa3SwJVIkyROaoVZE0